# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Sat Jun 19 16:17:06 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class ARIInfoClass(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ARIInfoClass.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.text_ctrl_20 = wx.TextCtrl(self, -1, "Information about ARI Compressor Map: \n\nCompressor map is based on a 20 degree Fahrenheit superheat.\n\nThe saturation temperatures are in degrees Fahrenheit, and the electrical power and mass flow rate are in units of W and lbm/h respectively.\n\nThe 10-coefficient ARI compressor map equation is shown below:", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.bitmap_4 = wx.StaticBitmap(self, -1, wx.Bitmap("imgs\\CompARIEqns.png", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ARIInfoClass.__set_properties
        self.SetTitle("ARI Map Information")
        self.text_ctrl_20.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ARIInfoClass.__do_layout
        sizer_25 = wx.BoxSizer(wx.VERTICAL)
        sizer_25.Add(self.text_ctrl_20, 1, wx.EXPAND, 0)
        sizer_25.Add(self.bitmap_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_25)
        sizer_25.Fit(self)
        self.Layout()
        # end wxGlade

# end of class ARIInfoClass


