# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Fri Jun 18 20:28:54 2010

import wx

# begin wxGlade: dependencies
from CircuitPlot import CircuitPlot
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class CircuitsClass(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CircuitsClass.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.pnlCircuits = CircuitPlot(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CircuitsClass.__set_properties
        self.SetTitle("CircuitsMap")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CircuitsClass.__do_layout
        sizer_24 = wx.BoxSizer(wx.VERTICAL)
        sizer_24.Add(self.pnlCircuits, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_24)
        sizer_24.Fit(self)
        self.Layout()
        # end wxGlade

# end of class CircuitsClass


