# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Mon Jul 05 22:02:37 2010

import wx

# begin wxGlade: dependencies
from PlotCycleOutputsPanel import PlotCycleOutputsPanel
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class SchematicFrameClass(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SchematicFrameClass.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.pnlSchematicDetailed = PlotCycleOutputsPanel(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SchematicFrameClass.__set_properties
        self.SetTitle("Schematic")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SchematicFrameClass.__do_layout
        sizer_38 = wx.BoxSizer(wx.VERTICAL)
        sizer_38.Add(self.pnlSchematicDetailed, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_38)
        sizer_38.Fit(self)
        self.Layout()
        # end wxGlade

# end of class SchematicFrameClass


