# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Fri Jun 18 17:35:49 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class FinsFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FinsFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_9 = wx.StaticText(self, -1, "Standard Fin Materials")
        self.lstFinMats = wx.ListBox(self, -1, choices=["Aluminum", "Copper"], style=wx.LB_SINGLE)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX, self.changeFins, self.lstFinMats)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FinsFrame.__set_properties
        self.SetTitle("Fins...")
        self.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_3DFACE))
        self.label_9.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.lstFinMats.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.lstFinMats.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FinsFrame.__do_layout
        sizer_22 = wx.BoxSizer(wx.VERTICAL)
        sizer_22.Add(self.label_9, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_22.Add((20, 20), 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_22.Add(self.lstFinMats, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_22)
        sizer_22.Fit(self)
        self.Layout()
        # end wxGlade
        
    def setTarget(self,target):
        self.target=target
    def setTitle(self,title):
        self.title=title

    def changeFins(self, event): # wxGlade: FinsFrame.<event_handler>
        
        if self.lstFinMats.GetStringSelection()=='Aluminum':
            self.target.SetValue('237')
        elif self.lstFinMats.GetStringSelection()=='Copper':
            self.target.SetValue('401')

# end of class FinsFrame


