# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Sat Jun 19 16:27:47 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class InsulationSelectClass(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: InsulationSelectClass.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_9_copy = wx.StaticText(self, -1, "Standard Insulation Materials")
        self.lstInsulation = wx.ListBox(self, -1, choices=["Armaflex", "Polystyrene"], style=wx.LB_SINGLE)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX, self.changeInsulation, self.lstInsulation)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: InsulationSelectClass.__set_properties
        self.SetTitle("frame_3")
        self.label_9_copy.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.lstInsulation.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.lstInsulation.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: InsulationSelectClass.__do_layout
        sizer_22_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_22_copy.Add(self.label_9_copy, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_22_copy.Add((20, 20), 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_22_copy.Add(self.lstInsulation, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_22_copy)
        sizer_22_copy.Fit(self)
        self.Layout()
        # end wxGlade
        
    def setTarget(self,target):
        self.target=target

    def changeInsulation(self, event): # wxGlade: InsulationSelectClass.<event_handler>
        if self.lstInsulation.GetStringSelection()=='Armaflex':
            self.target.SetValue('0.036')
        elif self.lstInsulation.GetStringSelection()=='Polystyrene':
            self.target.SetValue('0.027')

# end of class InsulationSelectClass


