# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Fri Jun 18 22:23:23 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class MyFrame3(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame3.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_10 = wx.StaticText(self, -1, "Material")
        self.cmbMaterial = wx.ComboBox(self, -1, choices=["Copper - Type L", "Steel - Schedule 40", "PVC - Schedule 40"], style=wx.CB_DROPDOWN)
        self.label_12 = wx.StaticText(self, -1, "Nom. Dimension")
        self.combo_box_2 = wx.ComboBox(self, -1, choices=["1/4 \"", "3/8 \"", "1/2 \"", "5/8 \"", "3/4 \"", "1 \"", "1-1/4 \"", "1-1/2 \"", "2 \""], style=wx.CB_DROPDOWN)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame3.__set_properties
        self.SetTitle("frame_4")
        self.label_10.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.cmbMaterial.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.cmbMaterial.SetSelection(1)
        self.label_12.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.combo_box_2.SetSelection(2)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame3.__do_layout
        grid_sizer_3 = wx.GridSizer(4, 2, 0, 0)
        grid_sizer_3.Add(self.label_10, 0, 0, 0)
        grid_sizer_3.Add(self.cmbMaterial, 0, 0, 0)
        grid_sizer_3.Add(self.label_12, 0, 0, 0)
        grid_sizer_3.Add(self.combo_box_2, 0, 0, 0)
        self.SetSizer(grid_sizer_3)
        grid_sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame3


